### ISSUE TITLE
moment.locale() throws TypeError

### ISSUE THREAD

**Issue by ewamarciniak** [moment/momentjs.com#171]
I am using moment,js as a bootstrap datimepicker dependency. Unfortunately am getting 
```TypeError: undefined is not a function``` in the console which ultimately prevents the datetimepicker from working correctly. Can you please have a look at this?. Thanks

**Comment by timrwood** [comment]
This sounds like its due to an older version of moment, `moment.locale()` was only added in `2.8.0`. See https://github.com/moment/moment/blob/develop/CHANGELOG.md#280-see-changelog

If your `moment.version` is greater than `2.8.0` and you are still experiencing this issue, please open an issue on the main https://github.com/moment/moment repo.

**Comment by charusat09** [comment]
Hey I am getting an error "TypeError: c is undefined".
I m using version 2.8.0 of moment. Could you please help me with it?
