### ISSUE TITLE
toDate not returning correct date after add

### ISSUE THREAD

**Issue by rtessler** [moment/momentjs.com#331]
var m = moment("12/01/2015", "DD/MM/YY");
var t1 = m.toDate();
var t2 = m.add(1, "hours").toDate();	
console.log("t1 = " + t1 + " t2 = " + t2 + " format = " + m.add(1, "hours").format());

produces:

t1 = Sun Jan 12 2020 01:00:00 GMT+1100 (AUS Eastern Daylight Time) t2 = Sun Jan 12 2020 01:00:00 GMT+1100 (AUS Eastern Daylight Time) format = 2020-01-12T02:00:00+11:00

**Comment by maggiepint** [comment]
A couple things:

You have a four digit year, so your tokens are wrong. This is why you're getting 2020. Do this instead:

```js
 moment("12/01/2015", "DD/MM/YYYY").format()
"2015-01-12T00:00:00-06:00"
```
Also, moments are mutable, as are javascript dates. When you call toDate on a moment in version 2.13, you get the date object that the moment holds internally. Then, when you call add when setting t2, you are mutating t1 as well. This is why t1 and t2 are the same in your log code.

The behavior in 2.14 will be changing to use a copy of moment's internal date, instead of returning it directly. When that happens, your t1 and t2 will be different, but do note that m will be mutated anyways.

**Comment by rtessler** [comment]
Ah I see, thanks
