### ISSUE TITLE
how to get and set relativeTimeThreshold year threshold?

### ISSUE THREAD

**Issue by FinalDes** [moment/momentjs.com#371]
how to get and set relativeTimeThreshold year threshold?

**Comment by antonama** [comment]
Could you please ask your question at http://stackoverflow.com/?
You could also try to search for momentjs tag on this site http://stackoverflow.com/questions/tagged/momentjs

Regarding your question - I think it is not possible now, since 
https://github.com/moment/moment/blob/b8a297c1f99b3918f44dd9e3d7bd59379a876ba6/src/lib/duration/humanize.js does not contain any reference to 'year'.
