### ISSUE TITLE
Feature Request: Locale Format for Date without Year

### ISSUE THREAD

**Issue by josephmferris** [moment/momentjs.com#423]
It would useful to have a small subset of locale-aware formats that would remove the year, showing just the month and day part of the date.  Simple string substitutions or regexes will not work for all cultures, especially on long formats, where additional words are used to describe the date.  Spanish would be a prime example of this, as the year would be shown as "de 2017".

**Comment by maggiepint** [comment]
While there's nothing wrong with your feature request per-say, I'm going to have to close it simply because it involves ALL the locales. If you were to search the main moment/moment repo, you would see that we get variations on this feature request all the time, and the bottom line is that if YOU want to find a way to validate that the locale format you added actually works in all locales by hunting down supporting data and the locale authors, you're more than welcome to. We will take your pull. However, it's not something that the maintainer team is up for doing.
I believe this format is in CLDR, so if you want to port it all over you're welcome to.
