### ISSUE TITLE
Duplication of 'Malay' locale on the website

### ISSUE THREAD

**Issue by megatheikal** [moment/momentjs.com#721]
**Describe the bug**
There are two locales have the same name and time.

**To Reproduce**
1. Open https://momentjs.com/ .
2. Scroll down to Multiple Locale Support section.
3. See that there are 2 'Malay' locales. 

**Expected behavior**
We expected to see a single 'Malay' locale.

**Screenshots**

![image](https://user-images.githubusercontent.com/64621442/160271025-c9cfc4e2-d5fa-4765-a18b-ba0cf3134ba7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser: Firefox
 - Version: 98.0.2

**Comment by gilmoreorless** [comment]
This is happening because there are duplicate locale files in the `moment` source, but [one of them is marked as deprecated](https://github.com/moment/moment/blob/000ac1800e620f770f4eb31b5ae908f6167b0ab2/src/locale/ms-my.js#L3).

I'll leave this issue open as a reminder to possibly exclude deprecated locales in the website build script.
