### ISSUE TITLE
zone() does not work as expected-- Docs need to be more explicit, should mention moment-timezone here. 

### ISSUE THREAD

**Issue by markstos** [moment/momentjs.com#97]
The docs for zone() say:

   "As of version 2.1.0, it is possible to set the offset by passing in the number of minutes offset from GMT."

Based on that, I would expect the following to take a time from the Eastern Time Zone and end up the the time expressed in UTC:

    console.log("should say 13:00: %s",moment("2014-01-08 8:00 AM").zone(300).toISOString());

However, if you run that an environment where the host time zone is UTC, it will produce the wrong result. (If you run it in Eastern Time, it works).  Based on that, it appears that zone(300) is not really "setting the offset" in this case. I'm not sure what's it's doing. The docs should clarify this. 

The following works, whether it is run from a host in the UTC time zone or the 'America/Indianapolis' time zone: 

    console.log("should say 13:00: %s",moment.tz("2014-01-08 8:00 AM","America/Indianapolis").toISOString());

Perhaps the zone() docs should be updated to recommend using moment-timezone() for the kinds of operations it can't reliably handle itself.  

It seems like Moment-timezone is going to be a better choice most of the time over zone(), as specific offsets don't take into account daylight savings time, while a time zone declaration like 'America/Indianapolis' will do that.

**Comment by malcolmocean** [comment]
I'll add that it might make sense to reference the sign change in the places where it says "`zone` is deprecated; use `utcOffset` instead". I went and did so blindly: huge mess. Dumb on my part of course, but not an unreasonable assumption, especially given the resemblance in name to getTimezoneOffset.

**Comment by mj1856** [comment]
I don't think this is an issue anymore.  Correct me if I'm wrong.  Thanks.

**Comment by markstos** [comment]
I confirmed that the original syntax in the post now throws a deprecation warning. 

Like @malcolmocean, I question the advice in the deprecation warning to "use utcOffset" instead. I took the original example and tried that:

```
process.env.TZ='UTC';
var moment = require('moment');
console.log("should say 13:00: %s",moment("2014-01-08 8:00 AM").utcOffset(300).toISOString());
console.log("should say 13:00: %s",moment("2014-01-08 8:00 AM").utcOffset(-300).toISOString());
console.log("should say 13:00: %s",moment("2014-01-08 8:00 AM").utcOffset(500).toISOString());
console.log("should say 13:00: %s",moment("2014-01-08 8:00 AM").utcOffset(-500).toISOString());
```

All of those cases result in the same result: `13:00: 2014-01-08T00:00:00.000Z`.   It appears specifying a utcOffset isn't doing anything to affect the parsing. 

Considering people are using `zone()`, when the deprecation warning is thrown, wouldn't recommending `moment-timezone` be more appropriate recomendation, since utcOffsets are not always the same thing as time as time zone offsets?

**Comment by mj1856** [comment]
When you call `.toISOString()`, the results are explicitly in UTC.  So it's ignoring any effects of changing the offset.  It would be better to use `.format()`, such that the result is shown with respect to that offset.

You are correct though that calling `utcOffset` doesn't affect the *parsing*.  Each function is processed individually, from left to right.  So in the above code, you're parsing a value in the local time zone, then converting it to a specific offset, then displaying it in UTC.

There are a few options to consider that will affect the *parsing*, such that the input value is taken with respect to the provided time zone:

1. `moment.utc("2014-01-08 08:00")` - will parse the value *in UTC*, and leave the resulting moment object in UTC mode.

2. `moment.tz("2014-01-08 08:00", "America/New_York")` - uses the moment-timezone add-on, and parses the value in the provided time zone, leaving the result in that time zone.  Uses named zones, not fixed offsets.

3. `moment("2014-01-08 08:00 +05:00").utcOffset(300)` - since the input value contains an offset, that offset is applied during the parsing, then the value is converted to the local time zone and the object is left in local mode.  Then calling `utcOffset` re-applies the offset, placing the object back into the original time zone.  Downside here is you have to pass the value twice, and it might be inconsistent.

4. `moment.parseZone("2014-01-08 08:00 +05:00")` - parses the input value, and leaves the moment object in the fixed zone that was specified in the input string.

As to which should be used, it depends on the specific kind of input you've got and exactly what functionality you need.  If you truly have datetime and offset as two separate fields as you showed in your example, and the offset is in terms of whole minutes instead of a hour/minute string, then instead of `parseZone`, do something like this:

```javascript
var input = "2014-01-08 8:00 AM";
var offset = 300;
var m = moment.utc(input, "YYYY-MM-DD h:mm A").add(offset, 'minutes').utcOffset(offset);
console.log(m.format()); // "2014-01-08T18:00:00+05:00"
```

I can see perhaps this could be useful as a built-in function.  I'll open an issue in the moment repo.
